interface Transcript {
  nim: string;
  nama: string;
  kodeMk1: string;
  namaMk1: string;
  nilai1: string;
  sks1: string;
  kodeMk2: string;
  namaMk2: string;
  nilai2: string;
  sks2: string;
  kodeMk3: string;
  namaMk3: string;
  nilai3: string;
  sks3: string;
  kodeMk4: string;
  namaMk4: string;
  nilai4: string;
  sks4: string;
  kodeMk5: string;
  namaMk5: string;
  nilai5: string;
  sks5: string;
  kodeMk6: string;
  namaMk6: string;
  nilai6: string;
  sks6: string;
  kodeMk7: string;
  namaMk7: string;
  nilai7: string;
  sks7: string;
  kodeMk8: string;
  namaMk8: string;
  nilai8: string;
  sks8: string;
  kodeMk9: string;
  namaMk9: string;
  nilai9: string;
  sks9: string;
  kodeMk10: string;
  namaMk10: string;
  nilai10: string;
  sks10: string;
  totalSks: string;
  ipk: string;
  keyId: number;
  publicKeyE: string;
  publicKeyN: string;
  signature: string;
  encryptKey: string;
  owner: string;
}

interface RecordType {
  nim: string;
  nama: string;
  kodeMk1: string;
  namaMk1: string;
  nilai1: string;
  sks1: string;
  kodeMk2: string;
  namaMk2: string;
  nilai2: string;
  sks2: string;
  kodeMk3: string;
  namaMk3: string;
  nilai3: string;
  sks3: string;
  kodeMk4: string;
  namaMk4: string;
  nilai4: string;
  sks4: string;
  kodeMk5: string;
  namaMk5: string;
  nilai5: string;
  sks5: string;
  kodeMk6: string;
  namaMk6: string;
  nilai6: string;
  sks6: string;
  kodeMk7: string;
  namaMk7: string;
  nilai7: string;
  sks7: string;
  kodeMk8: string;
  namaMk8: string;
  nilai8: string;
  sks8: string;
  kodeMk9: string;
  namaMk9: string;
  nilai9: string;
  sks9: string;
  kodeMk10: string;
  namaMk10: string;
  nilai10: string;
  sks10: string;
  totalSks: string;
  ipk: string;
  keyId: number;
  publicKeyE: string;
  publicKeyN: string;
  signature: string;
  encryptKey: string;
  owner: string;
  validated: string;
}

type Key =
  | "nim"
  | "nama"
  | "kodeMk1"
  | "namaMk1"
  | "nilai1"
  | "sks1"
  | "kodeMk2"
  | "namaMk2"
  | "nilai2"
  | "sks2"
  | "kodeMk3"
  | "namaMk3"
  | "nilai3"
  | "sks3"
  | "kodeMk4"
  | "namaMk4"
  | "nilai4"
  | "sks4"
  | "kodeMk5"
  | "namaMk5"
  | "nilai5"
  | "sks5"
  | "kodeMk6"
  | "namaMk6"
  | "nilai6"
  | "sks6"
  | "kodeMk7"
  | "namaMk7"
  | "nilai7"
  | "sks7"
  | "kodeMk8"
  | "namaMk8"
  | "nilai8"
  | "sks8"
  | "kodeMk9"
  | "namaMk9"
  | "nilai9"
  | "sks9"
  | "kodeMk10"
  | "namaMk10"
  | "nilai10"
  | "sks10"
  | "totalSks"
  | "ipk"
  | "keyId"
  | "publicKeyE"
  | "publicKeyN"
  | "signature"
  | "encryptKey"
  | "owner"
  | "validated";

export type { Transcript, RecordType, Key };
