const curriculum = [
    { kode: "MA1101", mataKuliah: "Matematika IA", SKS: 4 },
    { kode: "FI1101", mataKuliah: "Fisika Dasar IA", SKS: 4 },
    { kode: "KU1001", mataKuliah: "Olah Raga", SKS: 2 },
    { kode: "KU1102", mataKuliah: "Pengenalan Komputasi", SKS: 3 },
    { kode: "KU1011", mataKuliah: "Tata Tulis Karya Ilmiah", SKS: 2 },
    { kode: "KU1024", mataKuliah: "Bahasa Inggris", SKS: 2 },
    { kode: "MA1201", mataKuliah: "Matematika IIA", SKS: 4 },
    { kode: "FI1201", mataKuliah: "Fisika Dasar IIA", SKS: 4 },
    { kode: "IF1210", mataKuliah: "Dasar Pemrograman", SKS: 2 },
    { kode: "KU1202", mataKuliah: "Pengantar Rekayasa dan Desain", SKS: 3 },
    { kode: "KI1002", mataKuliah: "Kimia Dasar B", SKS: 4 },
    { kode: "EL1200", mataKuliah: "Pengantar Analisis Rangkaian", SKS: 2 },
    { kode: "II2130", mataKuliah: "Sistem dan Arsitektur Komputer", SKS: 3 },
    { kode: "II2110", mataKuliah: "Matematika STI", SKS: 3 },
    { kode: "II2111", mataKuliah: "Probabilitas dan Statistik", SKS: 3 },
    { kode: "TI3005", mataKuliah: "Organisasi & Manajemen Perusahaan Industri", SKS: 2 },
    { kode: "IF2140", mataKuliah: "Pemodelan Basis Data", SKS: 3 },
    { kode: "IF2111", mataKuliah: "Algoritma dan Struktur Data STI", SKS: 3 },
    { kode: "II2250", mataKuliah: "Manajemen Basis Data", SKS: 2 },
    { kode: "II2260", mataKuliah: "Sistem Embedded", SKS: 3 },
    { kode: "II2230", mataKuliah: "Jaringan Komputer", SKS: 3 },
    { kode: "II2220", mataKuliah: "Manajemen Sumber Daya STI", SKS: 3 },
    { kode: "II2240", mataKuliah: "Analisis Kebutuhan Sistem", SKS: 3 },
    { kode: "IF2212", mataKuliah: "Pemrograman Berorientasi Objek STI", SKS: 3 },
    { kode: "II3150", mataKuliah: "Sistem Multimedia", SKS: 3 },
    { kode: "II3160", mataKuliah: "Teknologi Sistem Terintegrasi", SKS: 3 },
    { kode: "II3120", mataKuliah: "Layanan Sistem dan Teknologi Informasi", SKS: 3 },
    { kode: "II3131", mataKuliah: "Interaksi Manusia Komputer", SKS: 3 },
    { kode: "II3121", mataKuliah: "Analisis Kebutuhan Enterprise", SKS: 3 },
    { kode: "IF3152", mataKuliah: "Rekayasa Perangkat Lunak STI", SKS: 3 },
    { kode: "II3260", mataKuliah: "Platform dan Pengembangan Aplikasi Mobile", SKS: 3 },
    { kode: "II3230", mataKuliah: "Keamanan Informasi", SKS: 3 },
    { kode: "II2221", mataKuliah: "Manajemen Proyek STI", SKS: 3 },
    { kode: "II3220", mataKuliah: "Arsitektur Enterprise", SKS: 3 },
    { kode: "II3240", mataKuliah: "Rekayasa Sistem dan Teknologi Informasi", SKS: 3 },
    { kode: "KU206X", mataKuliah: "Agama dan Etika", SKS: 2 },
    { kode: "II4090", mataKuliah: "Kerja Praktek", SKS: 2 },
    { kode: "II4091", mataKuliah: "Tugas Akhir 1 & Seminar", SKS: 2 },
    { kode: "II4370", mataKuliah: "Hukum & Etika Teknologi Informasi", SKS: 2 },
    { kode: "II4371", mataKuliah: "Kapita Selekta STI", SKS: 2 },
    { kode: "II4092", mataKuliah: "Tugas Akhir 2", SKS: 4 },
    { kode: "II4472", mataKuliah: "Komunikasi Interpersonal", SKS: 2 },
    { kode: "KU2071", mataKuliah: "Pancasila dan Kewarganegaraan", SKS: 2 },
    { kode: "XXLING", mataKuliah: "Mata Kuliah Wajib Lingkungan", SKS: 2 }
];

export default curriculum;